export { default as NavBar } from "./navBar";
export { default as Home } from "./home";
export { default as Footer } from "./footer";
export { default as Header } from "./header";
export { default as Expertise } from "./expertise";
export { default as Contact } from "./contact";
export { default as AboutMe } from "./aboutMe";
export { default as Hobbies } from "./hobbies";
export { default as Intros } from "./intros";
